apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-vote-app
  template:
    metadata:
      labels:
        app: web-vote-app
    spec:
      containers:
      - name: web-vote-app
        image: 114988434575.dkr.ecr.ap-southeast-3.amazonaws.com/web-vote-app:latest
        resources:
          requests:
            memory: 1024Mi
          limits:
            memory: 2048Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Jakarta
